
name: "setup"
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.PKG_ENGINES_NODE }}
      - run: npm install
      - run: npm run all
